apiVersion: v1
kind: Service
metadata:
  name: fleet-control-ui
  namespace: pg-prod
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4001
  selector:
    app: fleet-control-ui
    subdomain: fleet-control-ui
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-control-ui.deployment
  namespace: pg-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-control-ui
  template:
    metadata:
      labels:
        app: fleet-control-ui
        subdomain: fleet-control-ui
    spec:
      hostname: fleet-control-ui
      subdomain: fleet-control-ui
      containers:
        - name: fleet-control-ui
          image: hxreg.azurecr.io/fleet-control-ui
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secrets
          env:
            - name: APPSIGNAL_APP_NAME
              value: fleet_control_ui_kube-pg-prod
            - name: RELEASE_NODE
              value: fleet-control-ui@fleet-control-ui.fleet-control-ui
            - name: DISPATCH
              value: |
                [
                  quick_messages: [
                    "Please enter engine hours when safe",
                    "Tip please",
                    "Smoko after you tip thanks",
                    "Lunch after you tip thanks",
                    "Parkup after tip thanks", 
                    "Refuel now",
                  ],
                  track_method: :gps_gate,
                  settings: [
                    use_device_gps: true,
                    use_pre_starts: true,
                    prompt_exception_on_logout: true,
                    prompt_engine_hours_on_login: true,
                    prompt_engine_hours_on_logout: false,
                    prompt_pre_starts_on_login: true,
                    use_live_queue: false
                  ],
                  location_assignment_layout: [
                    orientation: "horizontal",
                    asset_order: "normal",
                    vertical: %{
                      order_by: "dig-unit",
                      columns: 2
                    },
                    horizontal: %{
                      order_by: "dig-unit"
                    }
                  ],
                  route_white_list: [
                    "/asset_assignment",
                    "/location_assignment",
                    "/mine_map",
                    "/operators",
                    "/asset_roster",
                    "/device_assignment",
                    "/asset_status",
                    "/time_allocation",
                    "/operator_time_allocation",
                    "/time_allocation_report",
                    "/time_code_editor",
                    "/message_editor",
                    "/engine_hours",
                    "/pre_start_editor",
                    "/pre_start_submissions",
                    "/asset_overview",
                    "/agents"
                  ],
                ]
