apiVersion: v1
kind: Service
metadata:
  name: fleet-control-ui
  namespace: wdl-test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4001
  selector:
    app: fleet-control-ui
    subdomain: fleet-control-ui
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-control-ui.deployment
  namespace: wdl-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-control-ui
  template:
    metadata:
      labels:
        app: fleet-control-ui
        subdomain: fleet-control-ui
    spec:
      hostname: fleet-control-ui
      subdomain: fleet-control-ui
      containers:
        - name: fleet-control-ui
          image: hxreg.azurecr.io/fleet-control-ui
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          imagePullPolicy: "Always"
          envFrom:
          - configMapRef:
              name: configmap
          - secretRef:
              name: secrets
          env:
            - name: APPSIGNAL_APP_NAME
              value: fleet_control_ui_kube-wdl-test
            - name: RELEASE_NODE
              value: fleet-control-ui@fleet-control-ui.fleet-control-ui
            - name: DISPATCH
              value: |
                [
                  quick_messages: [
                    "Smoko after tip",
                    "Blasting about to start",
                    ["Did you get this message", "Yes", "No"]
                  ],
                  track_method: :gps_gate,
                  settings: [
                    use_device_gps: false,
                    use_pre_starts: true,
                    prompt_exception_on_logout: true,
                    prompt_engine_hours_on_login: true,
                    prompt_engine_hours_on_logout: false,
                    prompt_pre_starts_on_login: true
                  ],
                  route_white_list: [
                    "/asset_assignment",
                    "/location_assignment",
                    "/mine_map",
                    "/operators",
                    "/asset_roster",
                    "/device_assignment",
                    "/asset_status",
                    "/time_allocation",
                    "/operator_time_allocation",
                    "/time_allocation_report",
                    "/time_code_editor",
                    "/message_editor",
                    "/engine_hours",
                    "/route_map",
                    "/pre_start_editor",
                    "/pre_start_submissions",
                    "/asset_overview",
                    "/agents"
                  ],
                ]
